Use build-ci-runner:rocky to interpolate spack recipes git variable, use rest api for changed-files action

diff --git a/.github/build-ci/actions/generate-manifest-matrix/action.yaml b/.github/build-ci/actions/generate-manifest-matrix/action.yaml
--- a/.github/build-ci/actions/generate-manifest-matrix/action.yaml
+++ b/.github/build-ci/actions/generate-manifest-matrix/action.yaml
@@ -24,6 +24,16 @@ outputs:
 runs:
   using: composite
   steps:
+    - name: Check for spack install
+      shell: bash
+      run: |
+        if [ ! -f /opt/spack/share/spack/setup-env.sh ]; then
+          echo "::error::Can't interrogate spack package recipes without a spack installation. Run this action as part of a container job of ghcr.io/access-nri/build-ci-runner"
+          exit 1
+        fi
+        . /opt/spack/share/spack/setup-env.sh
+        spack --version
+
     - name: Checkout fallback repository
       uses: actions/checkout@v6
       with:
@@ -62,6 +72,8 @@ runs:
       run: |
         pkgs="${{ inputs.packages }}"
 
+        . /opt/spack/share/spack/setup-env.sh
+
         for pkg in $pkgs; do
           # We want each manifest to have an associated injection of {{ package }} to $pkg
           # Replace underscores with hyphens for the template value, as spack converts directory underscores to package name hyphens
@@ -70,10 +82,10 @@ runs:
 
           ### Check for manifests from the packages associated GitHub repo, if it exists
 
-          # Extract OWNER/REPO directly when `git` points at GitHub.
-          repository=$(sed -nE "s|^\s*git\s*=\s*['\"]https://github\.com/([^/]+)/([^/'\"]+)['\"].*$|\1/\2|p" "$package_file" | head -n 1)
-          # Strip a trailing .git from the URL
-          repository="${repository%.git}"
+          # Extract git value from package.py using spack's python environment, which has access to the package repository metadata
+          repository_url=$(spack python -c "import spack.repo; print(spack.repo.PATH.get_pkg_class('$pkg').git)")
+          # Extract OWNER/REPO from repository_url
+          repository=$(echo "$repository_url" | sed -nE "s|^https://github\.com/([^/]+/[^/\.]+)(\.git)?$|\1|p")
 
           if [[ -n "$repository" ]]; then
             cloned_repo_path=$(mktemp -d "${RUNNER_TEMP}/package-manifest-repo-${pkg}-XXXXXX")
