stub: Simple solution to build build_systems like packages, with a package-specific set of manifests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,10 +3,16 @@ on:
   pull_request:
     paths:
       - spack_repo/access/nri/packages/**
+      - spack_repo/access/nri/build_systems/**
   workflow_dispatch:
     inputs:
       packages-to-test:
         description: 'Packages to test (space-separated)'
+        required: true
+        type: string
+        default: 'ALL'
+      build-systems-to-test:
+        description: 'Build system packages to test (space-separated)'
         required: true
         type: string
         default: 'ALL'
@@ -41,6 +47,7 @@ jobs:
       # Note, this needs to be updated in line with refs in the ci job below
       BUILD_CI_WORKFLOW_VERSION: v3
       PACKAGES_ROOT_DIR: spack_repo/access/nri/packages
+      BUILD_SYSTEMS_ROOT_DIR: spack_repo/access/nri/build_systems
     outputs:
       # Output both a matrix of {repo, ref, path, package}s, and a matrix of packages for exclusion
       matrix: ${{ steps.set-matrix.outputs.matrix }}
@@ -61,7 +68,9 @@ jobs:
           # We need to use the REST API because changed-files can't deduce $GITHUB_WORKSPACE correctly in a container
           use_rest_api: true
           dir_names: true
-          files: '${{ env.PACKAGES_ROOT_DIR }}/*/package.py'
+          files: |
+            ${{ env.PACKAGES_ROOT_DIR }}/*/package.py
+            ${{ env.BUILD_SYSTEMS_ROOT_DIR }}/*/package.py
 
       - name: PR - Normalize package paths to names
         id: set-matrix-pr
@@ -70,7 +79,7 @@ jobs:
         run: |
           normalized_pkgs=""
 
-          # From the full spack_repo/access/nri/packages/PKG path, to just the PKG
+          # From the full spack_repo/access/nri/*/PKG path, to just the PKG
           for pkg in ${{ steps.get-packages-changed.outputs.all_changed_files }}; do
             normalized_pkgs+="$(basename $pkg) "
           done
@@ -78,7 +87,7 @@ jobs:
           echo "pkgs=$normalized_pkgs" >> "$GITHUB_OUTPUT"
 
       - name: Dispatch - Get packages
-        id: set-matrix-dispatch
+        id: dispatch-packages
         if: github.event_name == 'workflow_dispatch'
         # Either get all packages defined (all subfolders under packages/) or use the input
         run: |
@@ -104,12 +113,42 @@ jobs:
 
           echo "pkgs=$pkgs" >> $GITHUB_OUTPUT
 
+      - name: Dispatch - Get build systems
+        id: dispatch-build-systems
+        if: github.event_name == 'workflow_dispatch'
+        # Either get all packages defined (all subfolders under build_systems/) or use the input
+        run: |
+          if [[ "${{ inputs.build-systems-to-test }}" == "ALL" ]]; then
+            pkgs=$(find ${{ env.BUILD_SYSTEMS_ROOT_DIR }}/ -mindepth 1 -maxdepth 1 -type d -printf '%P ')
+          else
+            pkgs="${{ inputs.build-systems-to-test }}"
+          fi
+
+
+          # Validate that all packages exist
+          error=false
+          for pkg in $pkgs; do
+            if [ ! -f "${{ env.BUILD_SYSTEMS_ROOT_DIR }}/$pkg/package.py" ]; then
+              echo "::error::build_systems/$pkg/package.py does not exist. Check spelling or if the package is defined."
+              error=true
+            fi
+          done
+
+          if [ "$error" = true ]; then
+            exit 1
+          fi
+
+          echo "pkgs=$pkgs" >> $GITHUB_OUTPUT
+
+      - name: Dispatch - Consolidate regular and build system packages
+        id: set-matrix-dispatch
+        run: echo "pkgs=${{ steps.dispatch-packages.outputs.pkgs }} ${{ steps.dispatch-build-systems.outputs.pkgs }}" >> $GITHUB_OUTPUT
+
       - name: Setup Matrix
         id: set-matrix
-        uses: access-nri/access-spack-packages/.github/build-ci/actions/generate-manifest-matrix@api-v2
+        uses: ./.github/build-ci/actions/generate-manifest-matrix
         with:
           packages: ${{ steps.set-matrix-pr.outputs.pkgs || steps.set-matrix-dispatch.outputs.pkgs }}
-          packages-root-dir: ${{ env.PACKAGES_ROOT_DIR }}
           ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.event.repository.default_branch }}
           token: ${{ secrets.SPACK_INSTALL_COMMAND_PAT }}
 
